[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "Flask-QRlabels"
version = "0.0.1"
dependencies = [
  'flask_login',
  'qrcode',
  'Pillow'
]
      
